# generated by datamodel-codegen:
#   filename:  ret-download.json
#   timestamp: 2024-09-28T15:20:03+00:00

from typing import List

from pydantic import BaseModel


class AvailableItem(BaseModel):
    downloadId: int
    collectionName: str
    datasetId: str
    displayId: str
    entityId: str
    eulaCode: str | None
    filesize: int
    label: str
    productCode: str
    productName: str
    statusCode: str
    statusText: str
    downloadApp: str
    url: str


class RequestedItem(BaseModel):
    downloadId: int
    collectionName: str
    datasetId: str
    displayId: str
    entityId: str
    eulaCode: str | None
    filesize: int
    label: str
    productCode: str
    productName: str
    statusCode: str
    statusText: str
    downloadApp: str
    url: str


class DownloadRetrieve(BaseModel):
    available: List[AvailableItem]
    queueSize: int
    requested: List[RequestedItem]
    eulas: List
