# generated by datamodel-codegen:
#   filename:  dwnld-options-2.json
#   timestamp: 2024-09-28T11:12:12+00:00

from typing import List, Optional

from pydantic import BaseModel


class SecondaryDownload(BaseModel):
    id: str
    downloadName: None
    displayId: str
    entityId: str
    datasetId: str
    available: bool
    filesize: int
    productName: str
    productCode: str
    bulkAvailable: bool
    downloadSystem: str
    secondaryDownloads: List
    fileGroups: None
    displayOrder: int


class DownloadOptions(BaseModel):
    id: str
    downloadName: Optional[str]
    displayId: str
    entityId: str
    datasetId: str
    available: bool
    filesize: int
    productName: str
    productCode: str
    bulkAvailable: bool
    downloadSystem: str
    secondaryDownloads: List[SecondaryDownload]
    fileGroups: None

class AvailableBandMetadata(BaseModel):
    productId: str
    entityId: str

    def to_dict(self):
        return self.model_dump()
