# generated by datamodel-codegen:
#   filename:  download_request.json
#   timestamp: 2024-09-28T15:42:09+00:00

from __future__ import annotations

from pydantic import BaseModel


class BandReadyToDownload(BaseModel):
    downloadId: int
    eulaCode: str | None
    url: str
