name: 🧹 Refactor
description: Refactor current code!
title: "[Refactor]: "
labels: [ "type: refactor" ]
body:
  - type: textarea
    id: whattochange
    attributes:
      label: What to refactor?
      description: Describe current code status and how to improve it.
      placeholder: Change function abc to...
    validations:
      required: true
